In [37]:
a=[]

for i  in  range(1,50):
    for j in range(1, i):
        print(j,end=" ")
    print(" ")

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5
1 2 3 4 5 6
1 2 3 4 5 6 7
1 2 3 4 5 6 7 8
1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9 10
1 2 3 4 5 6 7 8 9 10 11
1 2 3 4 5 6 7 8 9 10 11 12
1 2 3 4 5 6 7 8 9 10 11 12 13
1 2 3 4 5 6 7 8 9 10 11 12 13 14
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48

In [7]:
qw=2,3,4,5,6

In [38]:
for i in range(1, 7):
    print(i)

1
2
3
4
5
6

In [8]:
type(qw)

tuple

In [9]:
we=list(qw)

In [10]:
we

[2, 3, 4, 5, 6]

In [13]:
xc={"we","wd","sd"}

In [17]:
xcw={"Name":["pratap","singh"] ,"class":["1st","2nd"]}

In [19]:
type(xcw)

dict

In [20]:
xcw["region"]=("asia","europe")

In [21]:
xcw

{'Name': ['pratap', 'singh'],
 'class': ['1st', '2nd'],
 'region': ('asia', 'europe')}

In [25]:
a

[4,
 6,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [26]:
a.pop(-1)

48

In [41]:
a=("a","b","s","d","e","f","fv")

In [43]:
we=list(a)

In [44]:
type(we)

list

In [47]:
if a[:]==a[:-1]:
    print("Palindrome")
else:
    print("not")

not

In [49]:
class Name:
    def __init__(self,name):
        self.name=name
    def show(self):
        return print(f"name is {self.name}")

obj=Name("pratap")
obj.show()

name is pratap

In [58]:
wer="amma k tumake bhalobhashi"
wer

'amma k tumake bhalobhashi'

In [67]:
er=[1,2,34534,56,654,64746]

In [68]:
er

[1, 2, 34534, 56, 654, 64746]

In [70]:
import pandas as pd

In [76]:
df=pd.read_csv("cyberdata.csv",index_col=False)

In [80]:
df

,Unnamed: 0,durations,protocol_type,service,flags,src_bytes,dst_bytes,land,wrong_fragment,urgent,...,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level,attack_label
0,0,0,tcp,private,REJ,0,0,0,0,0,...,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21,1
1,1,2,tcp,ftp_data,SF,12983,0,0,0,0,...,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21,0
2,2,0,icmp,eco_i,SF,20,0,0,0,0,...,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15,1
3,3,1,tcp,telnet,RSTO,0,15,0,0,0,...,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11,1
4,4,0,tcp,http,SF,267,14515,0,0,0,...,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal,21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,22538,0,tcp,smtp,SF,794,333,0,0,0,...,0.06,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0
22539,22539,0,tcp,http,SF,317,938,0,0,0,...,0.00,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0
22540,22540,0,tcp,http,SF,54540,8314,0,0,0,...,0.00,0.00,0.00,0.00,0.0,0.07,0.07,back,15,1
22541,22541,0,udp,domain_u,SF,42,42,0,0,0,...,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal,21,0
22542,22542,0,tcp,sunrpc,REJ,0,0,0,0,0,...,0.03,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14,1

In [84]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [89]:
df

,durations,protocol_type,service,flags,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level,attack_label
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21,1
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21,0
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15,1
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11,1
4,0,tcp,http,SF,267,14515,0,0,0,0,...,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal,21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.06,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0
22539,0,tcp,http,SF,317,938,0,0,0,0,...,0.00,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0
22540,0,tcp,http,SF,54540,8314,0,0,0,2,...,0.00,0.00,0.00,0.00,0.0,0.07,0.07,back,15,1
22541,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal,21,0
22542,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.03,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14,1

In [90]:
df["prtocol"]=df.protocol_type.map(lambda x: 0 if x=='tcp' else 0)

In [91]:
df

,durations,protocol_type,service,flags,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level,attack_label,prtocol
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21,1,0
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.02,0.00,0.0,0.00,0.00,normal,21,0,0
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.28,0.00,0.0,0.00,0.00,saint,15,1,0
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11,1,0
4,0,tcp,http,SF,267,14515,0,0,0,0,...,0.01,0.03,0.01,0.0,0.00,0.00,normal,21,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0,0
22539,0,tcp,http,SF,317,938,0,0,0,0,...,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0,0
22540,0,tcp,http,SF,54540,8314,0,0,0,2,...,0.00,0.00,0.00,0.0,0.07,0.07,back,15,1,0
22541,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.00,0.00,0.00,0.0,0.00,0.00,normal,21,0,0
22542,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14,1,0

In [93]:
df

,durations,protocol_type,service,flags,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level,attack_label,prtocol
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21,1,0
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.02,0.00,0.0,0.00,0.00,normal,21,0,0
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.28,0.00,0.0,0.00,0.00,saint,15,1,0
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11,1,0
4,0,tcp,http,SF,267,14515,0,0,0,0,...,0.01,0.03,0.01,0.0,0.00,0.00,normal,21,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0,0
22539,0,tcp,http,SF,317,938,0,0,0,0,...,0.01,0.01,0.01,0.0,0.00,0.00,normal,21,0,0
22540,0,tcp,http,SF,54540,8314,0,0,0,2,...,0.00,0.00,0.00,0.0,0.07,0.07,back,15,1,0
22541,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.00,0.00,0.00,0.0,0.00,0.00,normal,21,0,0
22542,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14,1,0

In [94]:
sf=[1,2,3,43,2,34,4,3,34]

In [95]:
sf

[1, 2, 3, 43, 2, 34, 4, 3, 34]

In [96]:
sum(sf)

126

In [98]:
import numpy as np

In [99]:
arr=np.array([1,2,3,5,5,4,4,5,5])

In [102]:
arr.dtype

dtype('int32')

In [106]:
np.sort(arr)

array([1, 2, 3, 4, 4, 5, 5, 5, 5])

In [ ]:
arr1=np.array